services:
  tlsrpt-build:
    build:
      context: .
    image: localhost/tlsrpt

  tlsrpt-receiver:
    environment:
      MODE: receiver
    hostname: tlsrpt-receiver
    image: localhost/tlsrpt
    restart: always
    volumes:
    - tlsrpt-data:/tlsrpt-data:rw
    - tlsrpt-socket:/tlsrpt-socket:rw

  tlsrpt-reporter:
    environment:
      MODE: reporter
      SSMTP_MAILHUB: mailhub.example:25
      TLSRPT_REPORTER_CONTACT_INFO: tlsrpt@example.org
      TLSRPT_REPORTER_ORGANIZATION_NAME: example.org
      TLSRPT_REPORTER_SENDER_ADDRESS: tlsrpt-reporter@example.org
    hostname: tlsrpt-reporter
    image: localhost/tlsrpt
    restart: always
    volumes:
    - tlsrpt-data:/tlsrpt-data:rw

# postfix:
#   image: localhost/postfix
#   volumes:
#   - tlsrpt-socket:/var/spool/postfix/tlsrpt:rw

volumes:
  tlsrpt-data:
  tlsrpt-socket:
