services:
  tlsrpt-build:
    build:
      context: .
    image: localhost/tlsrpt

  tlsrpt-receiver:
    environment:
      MODE: receiver
      TLSRPT_RECEIVER_LOG_LEVEL: debug
    image: localhost/tlsrpt
    volumes:
    - tlsrpt-receiver-socket:/tlsrpt/socket:rw
    - tlsrpt-receiver-data:/var/lib/tlsrpt:rw

  postfix:
    entrypoint: /bin/sleep infinity
    image: andreasschulze.de/swbase/postfix
#   image: localhost/postfix
    volumes:
    - tlsrpt-receiver-socket:/var/spool/postfix/tlsrpt:rw

volumes:
  tlsrpt-receiver-socket:
  tlsrpt-receiver-data:
