services:
  tlsrpt-build:
    build:
      context: .
    image: localhost/tlsrpt

  tlsrpt-receiver:
    entrypoint: /bin/sleep infinity
    environment:
      MODE: receiver
    hostname: tlsrpt-receiver
    image: localhost/tlsrpt
    restart: always
    volumes:
    - tlsrpt-receiver-data:/var/lib/tlsrpt:rw
    - tlsrpt-receiver-socket:/tlsrpt/socket:rw

# postfix:
#   image: localhost/postfix
#   volumes:
#   - tlsrpt-receiver-socket:/var/spool/postfix/tlsrpt:rw

volumes:
  tlsrpt-receiver-socket:
  tlsrpt-receiver-data:
