#!/bin/sh

case "${MODE}" in
  receiver)
    if [ -z "${TLSRPT_RECEIVER_SOCKETNAME}" ]; then
      # see https://github.com/sys4/tlsrpt/issues/26
      # this way, postfix (and any other user) can write
      install -d --mode 0777 /tlsrpt-socket/
      umask 0000

      TLSRPT_RECEIVER_SOCKETNAME='/tlsrpt-receiver-socket/receiver.socket'
      export TLSRPT_RECEIVER_SOCKETNAME
    fi
    cmd='/usr/local/bin/tlsrpt-receiver'
    ;;
  *)
    cmd='/bin/bash'
    ;;
esac

exec $cmd
